"""
models/actuators/magnetorquers.py

Three-Axis Magnetorquer Model

Computes the magnetic control torque generated by an ideal
three-axis magnetorquer assembly.

Current Model
-------------
- Ideal actuator
- Instantaneous response
- Dipole saturation
- Orthogonal magnetorquer rods

Future Models
-------------
- First-order actuator dynamics
- Coil electrical dynamics
- Power consumption
- Thermal effects
- Coil failures
- Axis misalignment

References
----------
- Markley & Crassidis
- Wie
- ECSS-E-ST-60-30C
"""

import numpy as np


class Magnetorquers:
    """
    Three-axis ideal magnetorquer model.

    Parameters
    ----------
    max_dipole : float
        Maximum dipole moment generated by each rod [A·m²].
    """

    def __init__(
        self,
        max_dipole: float,
    ):

        if max_dipole <= 0.0:
            raise ValueError(
                "max_dipole must be positive."
            )

        self.max_dipole = float(max_dipole)

    # ==========================================================
    # Magnetic Control Torque
    # ==========================================================

    def compute(
        self,
        commanded_dipole: np.ndarray,
        magnetic_field_body: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Compute the magnetic control torque.

        Parameters
        ----------
        commanded_dipole : ndarray (3,)
            Commanded magnetic dipole [A·m²].

        magnetic_field_body : ndarray (3,)
            Geomagnetic field expressed in the body frame [Tesla].

        Returns
        -------
        actual_dipole : ndarray (3,)
            Saturated magnetic dipole [A·m²].

        body_torque : ndarray (3,)
            Generated control torque [N·m].
        """

        commanded_dipole = self._validate_vector(
            commanded_dipole,
            "commanded_dipole",
        )

        magnetic_field_body = self._validate_vector(
            magnetic_field_body,
            "magnetic_field_body",
        )

        actual_dipole = np.clip(
            commanded_dipole,
            -self.max_dipole,
            self.max_dipole,
        )

        body_torque = np.cross(
            actual_dipole,
            magnetic_field_body,
        )

        return actual_dipole, body_torque

    # ==========================================================
    # Utility Methods
    # ==========================================================

    @staticmethod
    def _validate_vector(
        vector: np.ndarray,
        name: str,
    ) -> np.ndarray:
        """
        Validate a 3-element vector.
        """

        vector = np.asarray(
            vector,
            dtype=float,
        )

        if vector.shape != (3,):
            raise ValueError(
                f"{name} must have shape (3,)."
            )

        if not np.all(
            np.isfinite(vector)
        ):
            raise ValueError(
                f"{name} contains invalid values."
            )

        return vector