"""
models/actuators/magnetorquers.py

Three-Axis Magnetorquer Model

Computes the magnetic control torque generated by an ideal
three-axis magnetorquer assembly.
"""

import numpy as np


class Magnetorquers:
    """
    Three-axis ideal magnetorquer model.

    Parameters
    ----------
    max_dipole : float | ndarray (3,)
        Maximum dipole moment [A·m²].

        - float  -> identical limit on all three axes
        - ndarray -> independent X/Y/Z limits
    """

    def __init__(
        self,
        max_dipole: float | np.ndarray,
    ):

        if np.isscalar(max_dipole):

            if max_dipole <= 0.0:
                raise ValueError(
                    "max_dipole must be positive."
                )

            self.max_dipole = np.full(
                3,
                float(max_dipole),
            )

        else:

            max_dipole = np.asarray(
                max_dipole,
                dtype=float,
            )

            if max_dipole.shape != (3,):
                raise ValueError(
                    "max_dipole must have shape (3,)."
                )

            if np.any(max_dipole <= 0.0):
                raise ValueError(
                    "All max_dipole values must be positive."
                )

            self.max_dipole = max_dipole

    # ==========================================================
    # Magnetic Control Torque
    # ==========================================================

    def compute(
        self,
        commanded_dipole: np.ndarray,
        magnetic_field_body: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:

        commanded_dipole = self._validate_vector(
            commanded_dipole,
            "commanded_dipole",
        )

        magnetic_field_body = self._validate_vector(
            magnetic_field_body,
            "magnetic_field_body",
        )

        actual_dipole = np.clip(
            commanded_dipole,
            -self.max_dipole,
            self.max_dipole,
        )

        body_torque = np.cross(
            actual_dipole,
            magnetic_field_body,
        )

        return actual_dipole, body_torque

    # ==========================================================
    # Utility
    # ==========================================================

    @staticmethod
    def _validate_vector(
        vector: np.ndarray,
        name: str,
    ) -> np.ndarray:

        vector = np.asarray(
            vector,
            dtype=float,
        )

        if vector.shape != (3,):
            raise ValueError(
                f"{name} must have shape (3,)."
            )

        if not np.all(np.isfinite(vector)):
            raise ValueError(
                f"{name} contains invalid values."
            )

        return vector